export const actionType={
     SET_PRODUCTS:"SET_PRODUCT",
     SELECTED_PRODUCTS:"",
     REMOVE_SELECTED_PRODUCTS:"",
     SET_USER:"SET_USER",
     SET_MESSAGE:"SET_MESSAGE",
     SET_LOADING:"SET_LOADING",
}